# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restoran', '0002_restorant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorant',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
